# Generated by Django 4.1.7 on 2023-03-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
    ]
